import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "GDG on campus DCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-grotesk">
        {children}
      </body>
    </html>
  );
}
